config/routes.rb
Rails.application.routes.draw do
  
  root "plainpage#index"
  
  get '/level/:id/:review' => "plainpage#index"
  get '/level/:id' => "plainpage#index", as: :level
  get '/dashboard' => "plainpage#dashboard"
  post "/code/send" => "plainpage#execute"
  patch '/next_level' => "plainpage#next_level"
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords" }

end

app/models/answer.rb
class Answer < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/plainpage_controller.rb
class PlainpageController < ApplicationController
  layout "dashboard", only: :dashboard
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, only: :execute
  
  def index
    if params.has_key?(:review) then
      if params[:id].to_i >= current_user.level then
        redirect_to level_path(current_user.level)
      else
        @level = Message.find(params[:id])
      end
    else
      if params.has_key?(:id) then
        if current_user.level > params[:id].to_i then
          redirect_to level_path(current_user.level)
        elsif current_user.level < params[:id].to_i then
          redirect_to level_path(current_user.level)
        else
          @level = Message.find(params[:id])
        end
      else
        redirect_to level_path(1) 
      end
    end
  end
  
  def execute
    respond_to do |format|
      format.json { render json: { result: 'true', data: params[:code] } }
    end
  end
  
  def dashboard
    @level = Message.all
    @isAdmin = current_user.isAdmin
  end
  
  def next_level
    user = User.find(current_user)
    if(params[:current_stage].to_i == user.level)
      level = user.level + 1
      user.update!(level: level)
    end
    respond_to do |format|
      format.json { render json: { result: 'true', data: user.level } }
    end
  end
  
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  layout "auth"
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  layout "auth"
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plainpage_helper.rb
module PlainpageHelper
end

app/views/layouts/auth.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>P:Recipe</title>
  <%= stylesheet_link_tag 'auth', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href='//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSans-kr.css' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
</head>
<body>

    <nav class="navbar navbar-light bg-faded">
      <a class="navbar-brand" href="#">
        <%= image_tag "precipe.png", height: "30px" %>
      </a>
    </nav>

    <main class="d-flex align-items-stretch">
        <div class="container">
            <%= yield %>
        </div>
    </main>
    
    <footer class="footer text-muted py-4">
      <div class="container">
        <div class="nav-logo">
          <%= image_tag "precipe.png", height: "50px" %>
        </div>
        <hr>
        <p>Project developed by J.W.Jeon, M.J.Na in the Paran Semester, Ajou University.</p>
      </div>
    </footer>

</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>P:Recipe</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'dashboard', media: 'all' %>
  <link href='//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSans-kr.css' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-ujs/1.2.2/rails.js"></script>
</head>
<body>

    <nav class="d-flex flex-row justify-content-between gnb navbar navbar-light bg-faded">
      <a class="navbar-brand" href="#">
        <%= image_tag "precipe.png", height: "30px" %>
      </a>
      <ul class="menu">
        <li><%= link_to "Home", root_path  %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      </ul>
    </nav>

    <main>
        <%= yield %>
    </main>
    
    <footer class="footer text-muted py-4">
      <div class="container">
        <div class="nav-logo">
          <%= image_tag "precipe.png", height: "50px" %>
        </div>
        <hr>
        <p>Project developed by J.W.Jeon, M.J.Na in the Paran Semester, Ajou University.</p>
      </div>
    </footer>

</body>
</html>

app/views/partials/_admin.html.erb
<div class="container">

    <div class="row row-offcanvas row-offcanvas-right mt-4">
    
      <div class="col-sm-12 col-md-3 sidebar-offanvas mb-4" id="sidebar">
        <div class="list-group">
          <a href="<%= request.path %>" class="list-group-item active">Dashboard</a>
          <a href="<%= edit_user_registration_path %>" class="list-group-item">Reset Password</a>
        </div>
      </div><!--/span-->
    
    
      <div class="col-sm-12 col-md-9">
        <div class="jumbotron">
          <h1>Hello, world!</h1>
          <p>This is an example to show the potential of an offcanvas layout pattern in Bootstrap. Try some responsive-range viewport sizes to see it in action.</p>
        </div>
        <div class="row">

          <% @level.each do |level| %>
          <div class="col-12 col-lg-4">
            <h2>Level <%= level.id %></h2>
            <p><%= level.content %></p>
            <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
          </div><!--/span-->
          <% end %>

        </div><!--/row-->
      </div><!--/span-->
    </div><!--/row-->
</div>

app/views/partials/_plain.html.erb
<div class="container">

    <div class="row row-offcanvas row-offcanvas-right mt-4">
    
      <div class="col-sm-12 col-md-3 sidebar-offanvas mb-4" id="sidebar">
        <div class="list-group">
          <a href="<%= request.path %>" class="list-group-item active">Dashboard</a>
          <a href="<%= edit_user_registration_path %>" class="list-group-item">Reset Password</a>
        </div>
      </div><!--/span-->
    
    
      <div class="col-sm-12 col-md-9">
        <div class="jumbotron">
          <h1>Dashboard</h1>
          <p>You can confirm how much you learn about programming concepts, and also can review the specific level of programming concepts.</p>
        </div>
        <div class="row">
          
          <% @level.each do |level| %>
          <div class="col-12 col-lg-4">
            <h2>Level <%= level.id %></h2>
            <p><%= level.content %></p>
            <p>
              <% if current_user.level > level.id %>
                <a class="btn btn-secondary" href="<%= level_path(level.id) %>/review" role="button">Review Again »</a>
              <% else %>
                <strong>You didn't finished this chapter yet.</strong>
              <% end %>
            </p>
          </div><!--/span-->
          <% end %>
          
        </div><!--/row-->
      </div><!--/span-->
    </div><!--/row-->
</div>

app/views/plainpage/dashboard.html.erb
<% if @isAdmin %>
    <%= render "partials/admin" %>
<% else %>
    <%= render "partials/plain" %>
<% end %>

app/views/plainpage/index.html.erb
<div class="preloader">
  <h1>LOADING</h1>
</div>

<div class="message">
  <% if params[:id].to_i == 1 && current_user.level == 1 then %>
  <div class="first card">
    <h1 class="title">Welcome!</h1>
    <h2 class="subtitle">We'll guide you to the wonderful programming world!</h2>
    <p class="desc">You have to use blocks to make a complete programmed code.<br>It sounds very awful. But don't worry. That'll be easy for you to study programming language.<br>We'll help you how to make the well-programmed code.</p>
    <button class="btn ghostBtn is-rounded" id="confirmClose">I got it!</button>
  </div>
  <% end %>
  
  <div class="target card">
    <h2><%= @level.title %></h2>
    <h3><%= @level.content %></h3>
    <button class="btn ghostBtn is-rounded" id="confirmFeedback">OK</button>
  </div>

  <div class="positive feedback card">
    <h2>성공!</h2>
    <h3><%= @level.positive %></h3>
    <button class="btn ghostBtn is-rounded" id="confirmResult">OK</button>
    <input type="hidden" value="positive" id="feedback_result"></input>
  </div>
  
  <div class="negative feedback card">
    <h2>실패!</h2>
    <h3><%= @level.negative %></h3>
    <button class="btn ghostBtn is-rounded" id="confirmTryAgain">Try Again</button>
    <input type="hidden" value="negative" id="feedback_result"></input>
  </div>
  
</div>

<div class="container">
  <div class="left-container">
    <div class="layer layer-50" id="workspace">
    </div>
    <div class="instruction">
        <h2><%= @level.title %></h2>
        <h3><%= @level.content %></h3>
    </div>
  </div>
  <div class="layer layer-50" id="converted">
    <nav class="gnb">
        <ul class="menu">
          <li><%= link_to "Dashboard", dashboard_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        </ul>
        <span class="nav-logo">P:Recipe</span>
    </nav>
    <div id="wrap">
      <section class="section contents-preview">
        <header>Your code blocks will be:</header>
        <div class="preview">
          <canvas id='resultCanvas'></canvas>
        </div>
        <button class="btn" id="play">Play the code!</button>
      </section>
      <section class="section code-preview">
        <header>Your code blocks will be converted to: </header>
        <div class="preview">
          <pre id="console">
            <code>
            </code>
          </pre>
        </div>
      </section>
    </div>
  </div>
</div>
<xml id="toolbox">
  <category name="Literal">
    <!--<block type="text"></block>-->
    <block type="math_number"></block>
    <block type="lists_create_empty"></block>
    <block type="lists_create_with"></block>
    <block type="logic_null"></block>
  </category>
  <category name="Variables" custom="VARIABLE"></category>
  <category name="Operators">
    <block type="logic_compare"></block>
    <block type="logic_operation"></block>
    <block type="logic_negate"></block>
    <block type="logic_boolean"></block>
    <block type="math_arithmetic"></block>
  </category>
  
  <category name="If">
    <block type="controls_if"></block>
    <block type="controls_if">
      <mutation else="1"></mutation>
    </block>
    <block type="controls_if">
      <mutation elseif="1" else="1"></mutation>
    </block>
  </category>
  <category name="Loops">
    <block type="controls_repeat_ext">
      <value name="TIMES">
        <block type="math_number">
          <field name="NUM">10</field>
        </block>
      </value>
    </block>
    <block type="controls_whileUntil"></block>
    <block type="controls_for">
      <field name="VAR">i</field>
      <value name="FROM">
        <block type="math_number">
          <field name="NUM">1</field>
        </block>
      </value>
      <value name="TO">
        <block type="math_number">
          <field name="NUM">10</field>
        </block>
      </value>
      <value name="BY">
        <block type="math_number">
          <field name="NUM">1</field>
        </block>
      </value>
    </block>
    <block type="controls_forEach"></block>
    <block type="controls_flow_statements"></block>
  </category>
  <category name="Lists">
    <block type="lists_create_empty"></block>
    <block type="lists_create_with"></block>
    <block type="lists_repeat">
      <value name="NUM">
        <block type="math_number">
          <field name="NUM">5</field>
        </block>
      </value>
    </block>
    <block type="lists_length"></block>
    <block type="lists_isEmpty"></block>
    <block type="lists_indexOf"></block>
    <block type="lists_getIndex"></block>
    <block type="lists_setIndex"></block>
  </category>
  <category name="Functions" custom="PROCEDURE"></category>
  <sep></sep>
  <category name="Library" expanded="true">
    <category name="반죽 붓기" >
      <block type="text_print">
        <value name="TEXT">
          <block type="text" collapsed="true">
            <field name="TEXT">틀이 비어있지 않아요</field>
          </block>
        </value>
      </block>
      <block type="text_print">
        <value name="TEXT">
          <block type="text" collapsed="true">
            <field name="TEXT">틀에 반죽을 부어요</field>
          </block>
        </value>
      </block>
    </category>
    <category name="앙금 넣기" >
      <block type="text" collapsed="true">
        <field name="TEXT">redbean</field>
      </block>
      <block type="text" collapsed="true">
        <field name="TEXT">cream</field>
      </block>
      <!--<block type="redbean">-->
      <!--</block>-->
      <block type="text_print">
        <value name="TEXT">
          <block type="text" collapsed="true">
            <field name="TEXT">redbean 앙금을 넣어요</field>
          </block>
        </value>
      </block>
      <block type="text_print">
        <value name="TEXT">
          <block type="text" collapsed="true">
            <field name="TEXT">cream 앙금을 넣어요</field>
          </block>
        </value>
      </block>
      <block type="text_print">
        <value name="TEXT">
          <block type="text" collapsed="true">
            <field name="TEXT">넣을 앙금이 없어요</field>
          </block>
        </value>
      </block>
    </category>
    <category name="뒤집기" >
      <block type="text_print">
        <value name="TEXT">
          <block type="text" collapsed="true">
            <field name="TEXT">틀을 뒤집어요</field>
          </block>
        </value>
      </block>
      <block type="text_print">
        <value name="TEXT">
          <block type="text" collapsed="true">
            <field name="TEXT">이미 틀이 뒤집어있어요</field>
          </block>
        </value>
      </block>
    </category>
    <category name="꺼내기" >
      <block type="text_print">
        <value name="TEXT">
          <block type="text" collapsed="true">
            <field name="TEXT">빵을 꺼내요</field>
          </block>
        </value>
      </block>
      <block type="text_print">
        <value name="TEXT">
          <block type="text" collapsed="true">
            <field name="TEXT">틀이 비어있어요</field>
          </block>
        </value>
      </block>
    </category>
    <category name="상태 확인하기" >
      <block type="text" collapsed="true">
        <field name="TEXT">ripe</field>
      </block>
      <block type="text" collapsed="true">
        <field name="TEXT">burnt</field>
      </block>
      <block type="text" collapsed="true">
        <field name="TEXT">raw</field>
      </block>
      <block type="text_print">
        <value name="TEXT">
          <block type="text" collapsed="true">
            <field name="TEXT">빵이 잘 익었어요</field>
          </block>
        </value>
      </block>
      <block type="text_print">
        <value name="TEXT">
          <block type="text" collapsed="true">
            <field name="TEXT">빵이 탔어요</field>
          </block>
        </value>
      </block>
      <block type="text_print">
        <value name="TEXT">
          <block type="text" collapsed="true">
            <field name="TEXT">빵이 덜 익었어요</field>
          </block>
        </value>
      </block>
    </category>
    <category name="FishBread">
      <!--<block type="text_print">
        <value name="TEXT"></value>
      </block>--->
      <block type="waiting_fishbread">
      </block>
      <block type="pour_fishbread">
      </block>
      <block type="pour_add_fishbread">
      </block>
      <block type="add_fishbread">
      </block>
      <block type="open_fishbread">
      </block>
      <block type="close_fishbread">
      </block>
      <block type="rotate_right_fishbread">
      </block>
      <block type="rotate_left_fishbread">
      </block>
      <block type="complete_fishbread">
      </block>
      <block type="burnt_fishbread">
      </block>
      <block type="less_ripe_fishbread">
      </block>
      <block type="add_blueberry_fishbread">
      </block>
      <block type="add_greentea_fishbread">
      </block>
      <block type="add_strawberry_fishbread">
      </block>
      <block type="repour_fishbread">
      </block>
      <block type="repour_strawberry_fishbread">
      </block>
      <block type="repour_blueberry_fishbread">
      </block>
      <block type="repour_greentea_fishbread">
      </block>
      <block type="reclose_fishbread">
      </block>
    </category>
    <category name="Math">
    <block type="math_single"></block>
    <block type="math_trig"></block>
    <block type="math_constant"></block>
    <block type="math_number_property"></block>
    <block type="math_round"></block>
    <block type="math_on_list"></block>
    <block type="math_modulo"></block>
    <block type="math_constrain">
      <value name="LOW">
        <block type="math_number">
          <field name="NUM">1</field>
        </block>
      </value>
      <value name="HIGH">
        <block type="math_number">
          <field name="NUM">100</field>
        </block>
      </value>
    </block>
    <block type="math_random_int">
      <value name="FROM">
        <block type="math_number">
          <field name="NUM">1</field>
        </block>
      </value>
      <value name="TO">
        <block type="math_number">
          <field name="NUM">100</field>
        </block>
      </value>
    </block>
    <block type="math_random_float"></block>
  </category>
  </category>
</xml>

   